name: SupremeTags
version: '${project.version}'
main: net.noscape.project.supremetags.SupremeTagsPremium
api-version: 1.13
depend: [NBTAPI]
softdepend: [PlaceholderAPI, HeadDatabase, VaultAPI]
authors: [DevScape]
folia-supported: true
description: Allow players to show of their supreme tags!