############################################################
# +------------------------------------------------------+ #
# |                     Settings                         | #
# +------------------------------------------------------+ #
############################################################

settings:
  default-tag: 'none' # set 'none' players start with no tag.
  forced-tag: false # this will make it force players to have a tag, they won't beable to take the tag off.
  categories: false # should supremetags use the category system?
  default-category: 'default' # used to set the tags category value when creating a new tag with the '/tag create' command
  update-check: true # the plugin will check if there is an update available.
  legacy-hex-format: true # should the plugin use the legacy hex colors? (&#d5b47 instead of #d5b47)
  auto-merge: false # auto merges all tags from deluxetags into supremetags (DeluxeTags is required on the server)
  active-tag-glow: true # adds a hidden enchantment to the tag item that is active for the player.
  cost-system: false # should your players be able to buy tags?
  cmi-color-support: false # allow the plugin to change color format to legacy '&x', to support CMI Chat, This will override 'legacy-hex-format'
  tag-command-in-disabled-worlds: true # should /tags command be disabled in 'disabled-worlds'.
  disabled-worlds: # what worlds should tags be allowed in, tags in this world will not be shown.
    - 'example'
    - 'world2'
  gui-messages: true # setting this to true, will enable 'tag-select-message' & 'reset-message'
  locked-view: false # this setting allows players to view locked/unlocked tags.
  personal-tags:
    enable: true # this setting allows players to make and access their own tags.
    limits:
      # permission limits: supremetags.mytags.limit.<group>
      ## example: supremetags.mytags.limit.default
      default: 10
      ## example: supremetags.mytags.limit.vip
      vip: 20
    format-replace: '%tag%' # strict format replacer.
  # layout types: [FULL, BORDER]
  # FULL - 36 tags
  # BORDER - 28 tags
  layout-type: 'BORDER'
  animated-tag-speed: 10 # in ticks
  tag-vouchers: true # should tag vouchers withdraw be enabled?

############################################################
# +------------------------------------------------------+ #
# |                    Messages                          | #
# +------------------------------------------------------+ #
############################################################

messages:
  tag-select-message: '&8[&6&lTags&8] &e%identifier% &7tag selected.'
  reset-message: '&8[&6&lTags&8] &7Reset tag.'
  insufficient-funds: '&cInsufficient funds. &7You need &c$%cost% &7to get this tag.'
  tag-unlocked: '&8[&6Tags&8] &7You have unlocked the tag: &6%identifier%'
  reload: '&8[&6&lTag&8] &7Reloaded plugin.'
  no-permission: '&cNo Permission.'
  no-tags: '&cYou have no tags yet.'
  tag-command-disabled: '&cTag command is disabled in this world.'
  invalid-tag: '&cThis tag does not exist.'
  valid-tag: '&cThis tag already exists.'
  invalid-category: '&cThis category does not exist.'
  locked-tag: '&cYou do not have access to select this tag!'
  stages:
    stage-1: '&6&lStage 1: &7Enter a name for the tag. &6&o(type in normal chat)'
    stage-2: '&6&lStage 2: &7What do you want the tag to look like? &6&o(type in normal chat)'
    complete: '&6&lComplete: &7New Tag: &6%identifier% &7- %tag% &7has been created.'

############################################################
# +------------------------------------------------------+ #
# |                       Data                           | #
# +------------------------------------------------------+ #
############################################################

# make sure you can check your panel database info to make sure everything is correct.
# Note: There are no extra steps needed for H2 or SQLite.
data:
  # types: [H2 / SQLite(RECOMMENDED OVER H2) / MYSQL / MARIADB(PREFERRED OVER MYSQL)]
  type: 'SQLite'

  # The address for the database server.
  # - to enable this part, change type to 'MYSQL' or 'MARIADB'
  # - some hosts can use your domain or server ip.
  address: 'host'
  # The standard DB engine port is used by default
  port: 3306
  # The name of the database to store tag data in.
  database: 'database'
  # Credentials for the database.
  username: 'user'
  password: 'pass'
  # leave this, if you don't know how to use options.
  options: 'useSSL=false&autoReconnect=true'

############################################################
# +------------------------------------------------------+ #
# |                       Gui                            | #
# +------------------------------------------------------+ #
############################################################

gui:
  main-menu:
    title: '&8Main Menu'
    size: 27
  tag-menu-none-categories: # edit the category title/items in the 'catorgies' area.
    title: '&8Tag Menu'
  tag-editor-menu:
    title: '&8Tag Editor'
    tag-item:
      displayname: '&7Tag: %tag%'
      lore:
        - '&7&m-----------------------------'
        - ''
        - '&bIdentifier: &7%identifier%'
        - ''
        - '&dDescription:'
        - '&7%description%'
        - ''
        - '&eClick to Edit!'
        - '&7&m-----------------------------'
  # disable items in the gui.
  # setting these values to false will not display the item in tag gui.
  items:
    ## WARNING ##
    # these default items names can't be changed!
    # but you can make new displayable static items.
    close:
      enable: true
      slot: 49
      displayname: '&c&lClose'
      material: 'BARRIER'
      custom-model-data: 0
      lore:
        - '&7Close the Menu!'
    reset:
      enable: true
      slot: 46
      displayname: '&c&lReset'
      material: 'RED_DYE'
      custom-model-data: 0
      lore:
        - '&7Reset your tag by to default!'
    glass: # this will only be disabled for 'FULL' layout type.
      enable: true
      displayname: '&c'
      material: 'GRAY_STAINED_GLASS_PANE'
      custom-model-data: 0
    personal-tags:
      enable: true
      slot: 8
      displayname: '&b&lPersonal Tags'
      material: 'ENDER_PEARL'
      custom-model-data: 0
      lore:
        - '&7Create your own tags!'
    # create tag is for personal tags menu
    create-tag:
      enable: true
      slot: 53
      displayname: '&b&lCreate a Tag'
      material: 'ENDER_PEARL'
      custom-model-data: 0
      lore:
        - '&7Create a new tag!'
    active:
      enable: true
      slot: 52
      displayname: '&6&l%player%'
      material: 'NAME_TAG'
      custom-model-data: 0
      lore:
        - '&7Your Active Tag: &6%identifier%'
    next:
      enable: true
      slot: 50
      displayname: '&f&lNext'
      material: 'ARROW'
      custom-model-data: 0
      lore:
        - '&7Go to the next page!'
    back:
      enable: true
      slot: 48
      displayname: '&f&lBack'
      material: 'ARROW'
      custom-model-data: 0
      lore:
        - '&7Go to the previous page!'